name: React Workflow
on:
  push:
    branches: [ main ]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: first task
        run: echo "start successfully"
            
            
      
