name: React Workflow
on:
  push:
    branches: [ main ]
jobs:
  flow1:
    runs-on: ubantu-latest
    steps:
      - name: first task
        run: echo "start successfully"
            
            
      
